# Pengelola
GET http://localhost:3001/pengelola

###
GET http://localhost:3001/pengelola/1
###
POST http://localhost:3001/pengelola
Content-Type: application/json

{
    "id_pengelola" : 2,
    "nama":"Muhammad Yusuf",
    "alamat":"Jl. Bandeng 12",
    "phone":"08953423422"
}


# Kecamatan
###
GET http://localhost:3001/kecamatan


# lapangan
###
GET http://localhost:3001/lapangan
###
GET http://localhost:3001/lapangan/7

###
POST http://localhost:3001/lapangan
content-type: application/json

{
    "id_lapangan": 8,
    "nama_lapangan": "Cipta Panorama Futsal",
    "alamat": "Jl. H. Risan No.31, RT.005/RW.010, Cipondoh Makmur, Kec. Cipondoh, Kota Tangerang, Banten 15148",
    "jumlah_lapangan": 2,
    "harga": 100000,
    "gambar": null,
    "jam_buka": "10:00",
    "jam_tutup": "00:00",
    "rating": 4,
    "note": "Tidak boleh membawa makanan atau minuman dari luar",
    "id_kecamatan": 1,
    "id_pengelola": 2
    
}
