# Pengelola
GET http://localhost:3001/pengelola

###
GET http://localhost:3001/pengelola/1
###
POST http://localhost:3001/pengelola
Content-Type: application/json

{
    "id_pengelola" : 2,
    "nama":"Muhammad Yusuf",
    "alamat":"Jl. Bandeng 12",
    "phone":"08953423422"
}


# Kecamatan
###
GET http://localhost:3001/kecamatan
###
GET http://localhost:3001/kecamatan/1/1

###
POST http://localhost:3001/kecamatan
Content-Type: application/json

{
    "id_kecamatan" : 12,
    "nama_kecamatan" : "Tanggerang"
}
###
PUT http://localhost:3001/kecamatan/1
Content-Type: application/json

{
    "id_kecamatan" : 1,
    "nama_kecamatan" : "Batuceper"
}




# lapangan
###
GET http://localhost:3001/lapangan
###
GET http://localhost:3001/lapangan/7

###
POST http://localhost:3001/lapangan
content-type: application/json

{
    "id_lapangan": 1,
    "nama_lapangan": "lapangan kacer",
    "alamat": "QJQ7+28X, Jl. Kakatua IV, RT.006/RW.012, Cibodasari, Kec. Cibodas, Kota Tangerang, Banten 15138",
    "jumlah_lapangan": null,
    "harga": 50000,
    "gambar": "images/kecamatan/Cibodas/Lapangan Kacer.png",
    "jam_buka": "08:00",
    "jam_tutup": "22:00",
    "rating": 5,
    "note": "Tidak boleh membawa makanan atau minuman dari luar",
    "id_kecamatan": 2,
    "id_pengelola": 2
}

###
GET http://localhost:3001/booking
###
GET http://localhost:3001/booking/3

###
POST http://localhost:3001/bookinglapangan
content_type : application/json

{
  "TanggalBooking": "2024-06-15",
  "jam_booking": "10:00:00",
  "durasi": "01:00:00",
  "nomor_lapangan": 2,
  "harga": 50000,
  "id_lapangan": 1,
  "id_pengguna": 1
}


###
GET http://localhost:3001/pengguna/1